package clicker;

import java.util.ArrayList;


public class Node {
	static enum TYPE {ROOT, SYMBOL, NUMBER, NUMBER_AGRESSIVE, SKIP, TERMINAL, SHIT};
	TYPE type;
	int value;
	static int rec = 0; // to where to write
	static int index = 0;
	ArrayList<Node> next;
	
	private static Node[][] store = new Node[2][500]; // [0] - weapon, [1] - armor
	public static Node weapon_root = new Node(){{type = TYPE.ROOT; next = new ArrayList<Node>();}};
	public static Node armor_root = new Node(){{type = TYPE.ROOT; next = new ArrayList<Node>();}};
	
	public static void addChilds(int node_n, int[] toAdd){
		for (int i = 0; i < toAdd.length; i++)
			store[rec][node_n].next.add(store[rec][toAdd[i]]);
	}
	public static void constructTree(){
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("+")); // 0
		createNode(Node.TYPE.NUMBER,           0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("%"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("-"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Minimum"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Dexterity"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Intelligence"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Strength"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Vitality"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Maximum"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId(".")); // 10
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         33);
		createNode(Node.TYPE.TERMINAL,         35);
		createNode(Node.TYPE.TERMINAL,         36);
		createNode(Node.TYPE.TERMINAL,         37);
		createNode(Node.TYPE.TERMINAL,         124);
		createNode(Node.TYPE.TERMINAL,         8);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Mana")); // 20
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Discipline"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fury"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Extra")); // miss
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Life"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Movement"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Life"));
		createNode(Node.TYPE.TERMINAL,         22);
		createNode(Node.TYPE.TERMINAL,         9);
		createNode(Node.TYPE.TERMINAL,         28); // 30
		createNode(Node.TYPE.TERMINAL,         31);
		createNode(Node.TYPE.TERMINAL,         29);
		createNode(Node.TYPE.TERMINAL,         30);
		createNode(Node.TYPE.TERMINAL,         84);
		createNode(Node.TYPE.TERMINAL,         71);
		createNode(Node.TYPE.TERMINAL,         114);
		createNode(Node.TYPE.SKIP,             22);  // miss
		createNode(Node.TYPE.TERMINAL,         12);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Humans"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Undead")); // 40
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Demons"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Beasts"));
		createNode(Node.TYPE.TERMINAL,         119);
		createNode(Node.TYPE.TERMINAL,         120);
		createNode(Node.TYPE.TERMINAL,         122);
		createNode(Node.TYPE.TERMINAL,         123);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cold"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fire"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Holy")); // 50
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lightning"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Resistance"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cold"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fire"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.TERMINAL,         2);
		createNode(Node.TYPE.TERMINAL,         3);
		createNode(Node.TYPE.TERMINAL,         4);
		createNode(Node.TYPE.TERMINAL,         5); // 60
		createNode(Node.TYPE.TERMINAL,         6);
		createNode(Node.TYPE.TERMINAL,         7);
		createNode(Node.TYPE.TERMINAL,         56);
		createNode(Node.TYPE.TERMINAL,         60);
		createNode(Node.TYPE.TERMINAL,         61);
		createNode(Node.TYPE.TERMINAL,         65);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, -1);
		createNode(Node.TYPE.SHIT,             -1);
		createNode(Node.TYPE.SHIT,             -1); // 70
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Increases"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Critical"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Attack"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hatred"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Mana"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Spirit Reg"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Haunt"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Plague"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Magic")); // 80
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Spirit Bar"));
		createNode(Node.TYPE.SKIP,             48); 
		createNode(Node.TYPE.SKIP,             81); 
		createNode(Node.TYPE.SKIP,             83); 
		createNode(Node.TYPE.SKIP,             82); 
		createNode(Node.TYPE.SKIP,             60); 
		createNode(Node.TYPE.SKIP,             68); 
		createNode(Node.TYPE.SKIP,             59); 
		createNode(Node.TYPE.SKIP,             104); // 90
		createNode(Node.TYPE.SKIP,             92); 
		createNode(Node.TYPE.SKIP,             83); 
		createNode(Node.TYPE.SKIP,             81); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Energy"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Overpower")); // 100
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Whirlwind"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Seismic"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Tempest"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Wave"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         0); // 110
		createNode(Node.TYPE.TERMINAL,         10);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         27);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.SKIP,             52); 
		createNode(Node.TYPE.SKIP,             15); 
		createNode(Node.TYPE.SKIP,             15); 
		createNode(Node.TYPE.SKIP,             41); 
		createNode(Node.TYPE.SKIP,             43); 
		createNode(Node.TYPE.SKIP,             53);  // 120
		createNode(Node.TYPE.TERMINAL,         39);
		createNode(Node.TYPE.TERMINAL,         40);
		createNode(Node.TYPE.TERMINAL,         42);
		createNode(Node.TYPE.TERMINAL,         52);
		createNode(Node.TYPE.TERMINAL,         53);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0); // 130
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         26);
		createNode(Node.TYPE.TERMINAL,         32);
		createNode(Node.TYPE.TERMINAL,         41);
		createNode(Node.TYPE.TERMINAL,         46);
		createNode(Node.TYPE.TERMINAL,         48);
		createNode(Node.TYPE.TERMINAL,         47);
		createNode(Node.TYPE.TERMINAL,         50); // 140
		createNode(Node.TYPE.TERMINAL,         51);
		createNode(Node.TYPE.NUMBER,           0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("%"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         85);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("%"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("of"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("CChance"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("chance")); // 150
		createNode(Node.TYPE.SKIP,             84); 
		createNode(Node.TYPE.SKIP,             13); 
		createNode(Node.TYPE.TERMINAL,         21);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Blind"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Chill"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fear"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Freeze"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Immobilize"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Knockback")); // 160
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Slow"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Stun"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("-"));
		createNode(Node.TYPE.TERMINAL,         13);
		createNode(Node.TYPE.TERMINAL,         14);
		createNode(Node.TYPE.TERMINAL,         15);
		createNode(Node.TYPE.TERMINAL,         16);
		createNode(Node.TYPE.TERMINAL,         17);
		createNode(Node.TYPE.TERMINAL,         18);
		createNode(Node.TYPE.TERMINAL,         19); // 170
		createNode(Node.TYPE.TERMINAL,         20);
		createNode(Node.TYPE.SKIP,             65); // very, блядь, special case 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         1);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Reduces"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("cooldown"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("resource"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("duration"));
		createNode(Node.TYPE.SKIP,             106); 
		createNode(Node.TYPE.SKIP,             34); // 180
		createNode(Node.TYPE.SKIP,             142); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Firebomb"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hammer"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lashing"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Zombie"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         54);
		createNode(Node.TYPE.SKIP,             15); 
		createNode(Node.TYPE.SKIP,             88);  // 190
		createNode(Node.TYPE.SKIP,             57); 
		createNode(Node.TYPE.SKIP,             58); 
		createNode(Node.TYPE.TERMINAL,         69);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         38);
		createNode(Node.TYPE.TERMINAL,         45);
		createNode(Node.TYPE.TERMINAL,         49); // 200
		createNode(Node.TYPE.TERMINAL,         55);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Adds")); // miss
		createNode(Node.TYPE.NUMBER,           0);
		createNode(Node.TYPE.SKIP,             30); // miss
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fire"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lightning"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.TERMINAL,         121);
		createNode(Node.TYPE.TERMINAL,         125);
		createNode(Node.TYPE.TERMINAL,         127); // 210
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Critical"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hits grant"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hit"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("CChance"));
		createNode(Node.TYPE.NUMBER,           0); 
		createNode(Node.TYPE.SKIP,             65); 
		createNode(Node.TYPE.SKIP,             97); // miss 
		createNode(Node.TYPE.TERMINAL,         25);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0); // 220
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         11);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         116);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Each"));
		createNode(Node.TYPE.SKIP,             53); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         23);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Gain")); // 230
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         126);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         24);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Ignores"));
		createNode(Node.TYPE.TERMINAL,         43);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Level"));
		createNode(Node.TYPE.SKIP,             125); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0); // 240
		createNode(Node.TYPE.TERMINAL,         44);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Monster"));
		createNode(Node.TYPE.SKIP,             57); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         34);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Regenerates"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         72);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Melee"));
		createNode(Node.TYPE.SKIP,             104); // 250
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         63);
		
		addChilds(0,   new int[]{1});
		addChilds(1,   new int[]{2, 3, 4, 5, 6, 7, 8, 9, 10, 27, 53, 54, 55, 56});
		addChilds(2,   new int[]{23, 24, 25, 26});
		addChilds(3,   new int[]{67});
		addChilds(4,   new int[]{17});
		addChilds(5,   new int[]{12});
		addChilds(6,   new int[]{13});
		addChilds(7,   new int[]{14});
		addChilds(8,   new int[]{15});
		addChilds(9,   new int[]{18, 19, 20, 21, 22});
		addChilds(10,  new int[]{11});
		addChilds(11,  new int[]{16});
		addChilds(18,  new int[]{29});
		addChilds(19,  new int[]{30});
		addChilds(20,  new int[]{31});
		addChilds(21,  new int[]{32});
		addChilds(22,  new int[]{33});
		addChilds(23,  new int[]{34});
		addChilds(24,  new int[]{35});
		addChilds(25,  new int[]{36});
		addChilds(26,  new int[]{37, 38});
		addChilds(27,  new int[]{28});
		addChilds(37,  new int[]{39, 40, 41, 42});
		addChilds(39,  new int[]{43});
		addChilds(40,  new int[]{44});
		addChilds(41,  new int[]{45});
		addChilds(42,  new int[]{46});
		addChilds(67,  new int[]{47, 48, 49, 50, 51, 52});
		addChilds(47,  new int[]{57});
		addChilds(48,  new int[]{58});
		addChilds(49,  new int[]{59});
		addChilds(50,  new int[]{60});
		addChilds(51,  new int[]{61});
		addChilds(52,  new int[]{62});
		addChilds(53,  new int[]{63});
		addChilds(54,  new int[]{64});
		addChilds(55,  new int[]{65});
		addChilds(56,  new int[]{66});
		addChilds(71,  new int[]{72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82});
		addChilds(72,  new int[]{88});
		addChilds(73,  new int[]{83});
		addChilds(74,  new int[]{84});
		addChilds(75,  new int[]{85});
		addChilds(76,  new int[]{86});
		addChilds(77,  new int[]{87});
		addChilds(78,  new int[]{89});
		addChilds(79,  new int[]{90});
		addChilds(80,  new int[]{91});
		addChilds(81,  new int[]{92});
		addChilds(82,  new int[]{93});
		addChilds(83,  new int[]{94});
		addChilds(84,  new int[]{95});
		addChilds(85,  new int[]{96});
		addChilds(86,  new int[]{97});
		addChilds(87,  new int[]{98});
		addChilds(88,  new int[]{99, 100, 101, 102, 103, 104});
		addChilds(89,  new int[]{105});
		addChilds(90,  new int[]{106});
		addChilds(91,  new int[]{107});
		addChilds(92,  new int[]{108});
		addChilds(93,  new int[]{109});
		addChilds(94,  new int[]{110});
		addChilds(95,  new int[]{111});
		addChilds(96,  new int[]{112});
		addChilds(97,  new int[]{113});
		addChilds(98,  new int[]{114});
		addChilds(99,  new int[]{115});
		addChilds(100, new int[]{116});
		addChilds(101, new int[]{117});
		addChilds(102, new int[]{118});
		addChilds(103, new int[]{119});
		addChilds(104, new int[]{120});
		addChilds(105, new int[]{121});
		addChilds(106, new int[]{122});
		addChilds(107, new int[]{123});
		addChilds(108, new int[]{124});
		addChilds(109, new int[]{125});
		addChilds(112, new int[]{126});
		addChilds(114, new int[]{127});
		addChilds(115, new int[]{128});
		addChilds(116, new int[]{129});
		addChilds(117, new int[]{130});
		addChilds(118, new int[]{131});
		addChilds(119, new int[]{132});
		addChilds(120, new int[]{133});
		addChilds(126, new int[]{134});
		addChilds(127, new int[]{135});
		addChilds(128, new int[]{136});
		addChilds(129, new int[]{137});
		addChilds(130, new int[]{138});
		addChilds(131, new int[]{139});
		addChilds(132, new int[]{140});
		addChilds(133, new int[]{141});
		addChilds(142, new int[]{143, 144});
		addChilds(143, new int[]{145});
		addChilds(144, new int[]{146});
		addChilds(146, new int[]{147});
		addChilds(147, new int[]{148, 149, 150});
		addChilds(148, new int[]{153});
		addChilds(149, new int[]{152});
		addChilds(150, new int[]{151});
		addChilds(151, new int[]{154});
		addChilds(152, new int[]{155, 156, 157, 158, 159, 160, 161, 162});
		addChilds(154, new int[]{163});
		addChilds(155, new int[]{164});
		addChilds(156, new int[]{165});
		addChilds(157, new int[]{166});
		addChilds(158, new int[]{167});
		addChilds(159, new int[]{168});
		addChilds(160, new int[]{169});
		addChilds(161, new int[]{170});
		addChilds(162, new int[]{171});
		addChilds(163, new int[]{68});
		addChilds(68,  new int[]{172});
		addChilds(172, new int[]{173});
		addChilds(173, new int[]{174});
		addChilds(175, new int[]{176, 177, 178});
		addChilds(176, new int[]{179});
		addChilds(177, new int[]{180});
		addChilds(178, new int[]{181});
		addChilds(179, new int[]{182});
		addChilds(180, new int[]{183, 184, 185, 186});
		addChilds(181, new int[]{187});
		addChilds(182, new int[]{188});
		addChilds(183, new int[]{189});
		addChilds(184, new int[]{190});
		addChilds(185, new int[]{191});
		addChilds(186, new int[]{192});
		addChilds(187, new int[]{193});
		addChilds(189, new int[]{194});
		addChilds(190, new int[]{195});
		addChilds(191, new int[]{196});
		addChilds(192, new int[]{197});
		addChilds(194, new int[]{198});
		addChilds(195, new int[]{199});
		addChilds(196, new int[]{200});
		addChilds(197, new int[]{201});
		addChilds(202, new int[]{203});
		addChilds(203, new int[]{204});
		addChilds(204, new int[]{205, 206, 207});
		addChilds(205, new int[]{208});
		addChilds(206, new int[]{209});
		addChilds(207, new int[]{210});
		addChilds(211, new int[]{212, 213});
		addChilds(212, new int[]{216});
		addChilds(213, new int[]{214, 215});
		addChilds(214, new int[]{217});
		addChilds(215, new int[]{218});
		addChilds(216, new int[]{219});
		addChilds(217, new int[]{220});
		addChilds(218, new int[]{221});
		addChilds(220, new int[]{222});
		addChilds(221, new int[]{223});
		addChilds(223, new int[]{224});
		addChilds(224, new int[]{225});
		addChilds(226, new int[]{227});
		addChilds(227, new int[]{228});
		addChilds(228, new int[]{229});
		addChilds(230, new int[]{231});
		addChilds(231, new int[]{232, 233});
		addChilds(232, new int[]{234});
		addChilds(234, new int[]{235});
		addChilds(236, new int[]{237});
		addChilds(238, new int[]{239});
		addChilds(239, new int[]{240});
		addChilds(240, new int[]{241});
		addChilds(242, new int[]{243});
		addChilds(243, new int[]{244});
		addChilds(244, new int[]{245});
		addChilds(246, new int[]{247});
		addChilds(247, new int[]{248});
		addChilds(249, new int[]{250});
		addChilds(250, new int[]{251});
		addChilds(251, new int[]{252});
		
		weapon_root.next.add(store[rec][0]);
		weapon_root.next.add(store[rec][71]);
		weapon_root.next.add(store[rec][142]);
		weapon_root.next.add(store[rec][175]);
		weapon_root.next.add(store[rec][202]);
		weapon_root.next.add(store[rec][211]);
		weapon_root.next.add(store[rec][226]);
		weapon_root.next.add(store[rec][230]);
		weapon_root.next.add(store[rec][236]);
		weapon_root.next.add(store[rec][238]);
		weapon_root.next.add(store[rec][242]);
		weapon_root.next.add(store[rec][246]);
		weapon_root.next.add(store[rec][249]);
		
		switchToArmor();
		
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("+"));
		createNode(Node.TYPE.NUMBER,           0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Minimum"));
        createNode(Node.TYPE.SYMBOL,           Utils.getResId("Maximum"));
        createNode(Node.TYPE.SYMBOL,           Utils.getResId("Life"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Dexterity"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Intelligence"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Strength"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Vitality"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("-"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Resistance"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Armor"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cold"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fire"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lightning"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Physical"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("%"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Mana"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Discipline"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fury"));
		createNode(Node.TYPE.TERMINAL,         8);
		createNode(Node.TYPE.TERMINAL,         22);
		createNode(Node.TYPE.TERMINAL,         33);
		createNode(Node.TYPE.TERMINAL,         35);
		createNode(Node.TYPE.TERMINAL,         36);
		createNode(Node.TYPE.TERMINAL,         37);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("n"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 56);
		createNode(Node.TYPE.TERMINAL,         57);
		createNode(Node.TYPE.TERMINAL,         58);
		createNode(Node.TYPE.TERMINAL,         60);
		createNode(Node.TYPE.TERMINAL,         61);
		createNode(Node.TYPE.TERMINAL,         62);
		createNode(Node.TYPE.TERMINAL,         64);
		createNode(Node.TYPE.TERMINAL,         65);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("CChance"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Movement"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Extra"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Life"));
		createNode(Node.TYPE.TERMINAL,         9);
		createNode(Node.TYPE.TERMINAL,         28);
		createNode(Node.TYPE.TERMINAL,         31);
		createNode(Node.TYPE.TERMINAL,         29);
		createNode(Node.TYPE.TERMINAL,         30);
		createNode(Node.TYPE.TERMINAL,         118);
		createNode(Node.TYPE.TERMINAL,         59);
		createNode(Node.TYPE.TERMINAL,         122);
		createNode(Node.TYPE.TERMINAL,         114);
		createNode(Node.TYPE.TERMINAL,         84); 
		createNode(Node.TYPE.TERMINAL,         71);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Increases"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Attack"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hatred"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Mana"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Spirit Reg"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Spirit Bar"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Elemental"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Bola"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Spike"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Crippl	ing"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Deadly"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Exploding"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Gold"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Critical"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Entagliny"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hungering"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDuration"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Shock"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Spectral"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Bash"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cleave"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Frenzy"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Evasive"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Grenades"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fists"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Sweeping"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Way"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Locust"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Elecrolute"));
		createNode(Node.TYPE.SKIP,             76); 
		createNode(Node.TYPE.SKIP,             122); 
		createNode(Node.TYPE.SKIP,             123); 
		createNode(Node.TYPE.SKIP,             122); 
		createNode(Node.TYPE.SKIP,             91); 
		createNode(Node.TYPE.SKIP,             120); 
		createNode(Node.TYPE.SKIP,             120);
		createNode(Node.TYPE.SKIP,             131); 
		createNode(Node.TYPE.SKIP,             123); 
		createNode(Node.TYPE.SKIP,             124); 
		createNode(Node.TYPE.SKIP,             133); 
		createNode(Node.TYPE.SKIP,             138); 
		createNode(Node.TYPE.SKIP,             127); 
		createNode(Node.TYPE.SKIP,             154); 
		createNode(Node.TYPE.SKIP,             103); 
		createNode(Node.TYPE.SKIP,             123); 
		createNode(Node.TYPE.SKIP,             132); 
		createNode(Node.TYPE.SKIP,             101); 
		createNode(Node.TYPE.SKIP,             131); 
		createNode(Node.TYPE.SKIP,             131); 
		createNode(Node.TYPE.SKIP,             89); 
		createNode(Node.TYPE.SKIP,             87); 
		createNode(Node.TYPE.SKIP,             87); 
		createNode(Node.TYPE.SKIP,             118); 
		createNode(Node.TYPE.SKIP,             87); 
		createNode(Node.TYPE.SKIP,             167); 
		createNode(Node.TYPE.SKIP,             127); 
		createNode(Node.TYPE.SKIP,             303); 
		createNode(Node.TYPE.SKIP,             0); // add skip 114
		createNode(Node.TYPE.SKIP,             0); // add skip 115
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Overpower"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Whirlwind"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Seismic"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Tempest"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Wave"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Acid"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Multishot"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Rapid"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Revenge"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         0);
		createNode(Node.TYPE.TERMINAL,         10);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         27);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         52);
		createNode(Node.TYPE.TERMINAL,         53);
		createNode(Node.TYPE.TERMINAL,         74);
		createNode(Node.TYPE.TERMINAL,         73);
		createNode(Node.TYPE.TERMINAL,         96);
		createNode(Node.TYPE.TERMINAL,         97);
		createNode(Node.TYPE.TERMINAL,         99);
		createNode(Node.TYPE.TERMINAL,         100);
		createNode(Node.TYPE.TERMINAL,         115);
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             63); 
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             122); 
		createNode(Node.TYPE.SKIP,             79); 
		createNode(Node.TYPE.SKIP,             0); // add skip 174
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             53); 
		createNode(Node.TYPE.SKIP,             52); 
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.TERMINAL,         75);
		createNode(Node.TYPE.TERMINAL,         76);
		createNode(Node.TYPE.TERMINAL,         80);
		createNode(Node.TYPE.TERMINAL,         82);
		createNode(Node.TYPE.TERMINAL,         83);
		createNode(Node.TYPE.TERMINAL,         86);
		createNode(Node.TYPE.TERMINAL,         87);
		createNode(Node.TYPE.TERMINAL,         88);
		createNode(Node.TYPE.TERMINAL,         93);
		createNode(Node.TYPE.TERMINAL,         94);
		createNode(Node.TYPE.TERMINAL,         101);
		createNode(Node.TYPE.TERMINAL,         102);
		createNode(Node.TYPE.TERMINAL,         103);
		createNode(Node.TYPE.TERMINAL,         106);
		createNode(Node.TYPE.TERMINAL,         110);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         26);
		createNode(Node.TYPE.TERMINAL,         32);
		createNode(Node.TYPE.TERMINAL,         46);
		createNode(Node.TYPE.TERMINAL,         47);
		createNode(Node.TYPE.TERMINAL,         48);
		createNode(Node.TYPE.TERMINAL,         50);
		createNode(Node.TYPE.TERMINAL,         51);
		createNode(Node.TYPE.TERMINAL,         104);
		createNode(Node.TYPE.TERMINAL,         77);
		createNode(Node.TYPE.TERMINAL,         78);
		createNode(Node.TYPE.TERMINAL,         79);
		createNode(Node.TYPE.TERMINAL,         90);
		createNode(Node.TYPE.NUMBER,           0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("%"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         85);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("%"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("CChance"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("chance"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("of"));
		createNode(Node.TYPE.SKIP,             124); 
		createNode(Node.TYPE.SKIP,             20); 
		createNode(Node.TYPE.TERMINAL,         21);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Blind"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Chill"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fear"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Freeze"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Immobilize"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Knockback"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Slow"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Stun"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("-"));
		createNode(Node.TYPE.TERMINAL,         13);
		createNode(Node.TYPE.TERMINAL,         14);
		createNode(Node.TYPE.TERMINAL,         15);
		createNode(Node.TYPE.TERMINAL,         16);
		createNode(Node.TYPE.TERMINAL,         17);
		createNode(Node.TYPE.TERMINAL,         18);
		createNode(Node.TYPE.TERMINAL,         19);
		createNode(Node.TYPE.TERMINAL,         20);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SKIP,             60); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         1);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Adds"));
		createNode(Node.TYPE.NUMBER,           0);
		createNode(Node.TYPE.SKIP,             20); 
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Fire"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Poison"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Holy"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lightning"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cold"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.TERMINAL,         121);
		createNode(Node.TYPE.TERMINAL,         127);
		createNode(Node.TYPE.TERMINAL,         128);
		createNode(Node.TYPE.TERMINAL,         125);
		createNode(Node.TYPE.TERMINAL,         132);
		createNode(Node.TYPE.TERMINAL,         131);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Critical"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hit"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hits grant"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("DDamage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("CChance"));
		createNode(Node.TYPE.NUMBER,           0); 
		createNode(Node.TYPE.SKIP,             97); 
		createNode(Node.TYPE.SKIP,             97); 
		createNode(Node.TYPE.TERMINAL,         25);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         11);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         116);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Each"));
		createNode(Node.TYPE.SKIP,             75);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         23);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Gain"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("."));
		createNode(Node.TYPE.TERMINAL,         126);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         24);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Ignores"));
		createNode(Node.TYPE.TERMINAL,         43);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Level"));
		createNode(Node.TYPE.SKIP,             186); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         44);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Monster"));
		createNode(Node.TYPE.SKIP,             -1); // add skip 299
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         34);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Regenerates"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         72);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Melee"));
		createNode(Node.TYPE.SKIP,             104); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         63);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Attack"));
		createNode(Node.TYPE.SKIP,             147); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         117);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Health"));
		createNode(Node.TYPE.SKIP,             110); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         70);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Reduces"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("damage"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("resource"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("cooldown"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("duration"));
		createNode(Node.TYPE.SKIP,             38); 
		createNode(Node.TYPE.SKIP,             156); 
		createNode(Node.TYPE.SKIP,             210); 
		createNode(Node.TYPE.SKIP,             55); 
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lighting"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cold"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("elites"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("melee"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("ranged"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Wall"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Summon"));
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Desintagrate"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hydra"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Lashing"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Zombie"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Meteor"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Rend"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Weapon"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Chakram"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Impale"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cyclone"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Arcane"));
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Firebats"));
		createNode(Node.TYPE.SKIP,             77); 
		createNode(Node.TYPE.SKIP,             77); 
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             77); 
		createNode(Node.TYPE.SKIP,             7); 
		createNode(Node.TYPE.SKIP,             156); 
		createNode(Node.TYPE.SKIP,             0); // add skip 352
		createNode(Node.TYPE.TERMINAL,         69);
		createNode(Node.TYPE.SKIP,             0); // add skip 354
		createNode(Node.TYPE.SKIP,             0); // add skip 355
		createNode(Node.TYPE.SKIP,             84); 
		createNode(Node.TYPE.SKIP,             84); 
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             70); 
		createNode(Node.TYPE.SKIP,             23);
		createNode(Node.TYPE.SKIP,             23); 
		createNode(Node.TYPE.SKIP,             66); 
		createNode(Node.TYPE.SKIP,             0); // add skip 364
		createNode(Node.TYPE.SKIP,             0); // add skip 365
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         129);
		createNode(Node.TYPE.TERMINAL,         130);
		createNode(Node.TYPE.TERMINAL,         66);
		createNode(Node.TYPE.TERMINAL,         67);
		createNode(Node.TYPE.TERMINAL,         68);
		createNode(Node.TYPE.TERMINAL,         54);
		createNode(Node.TYPE.TERMINAL,         107);
		createNode(Node.TYPE.TERMINAL,         109);
		createNode(Node.TYPE.TERMINAL,         112);
		createNode(Node.TYPE.TERMINAL,         49);
		createNode(Node.TYPE.TERMINAL,         55);
		createNode(Node.TYPE.TERMINAL,         81);
		createNode(Node.TYPE.TERMINAL,         89);
		createNode(Node.TYPE.TERMINAL,         91);
		createNode(Node.TYPE.TERMINAL,         92);
		createNode(Node.TYPE.TERMINAL,         95);
		createNode(Node.TYPE.TERMINAL,         98);
		createNode(Node.TYPE.TERMINAL,         108);
		createNode(Node.TYPE.TERMINAL,         105);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Hammer"));
		createNode(Node.TYPE.SKIP,             183); 
		createNode(Node.TYPE.NUMBER_AGRESSIVE, 0);
		createNode(Node.TYPE.TERMINAL,         45);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Strafe"));
		createNode(TYPE.SKIP,                  0);
		createNode(TYPE.NUMBER_AGRESSIVE,      0);
		createNode(TYPE.TERMINAL,              133);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Cluster"));
		createNode(TYPE.SKIP,                  66);
		createNode(TYPE.NUMBER_AGRESSIVE,      0);
		createNode(TYPE.TERMINAL,              134);
		createNode(Node.TYPE.SYMBOL,           Utils.getResId("Corpse"));
		createNode(TYPE.SKIP,                  145);
		createNode(TYPE.NUMBER_AGRESSIVE,      0);
		createNode(TYPE.TERMINAL,              135);
		
                
		addChilds(0,   new int[]{1});
		addChilds(1,   new int[]{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18});
		addChilds(2,   new int[]{24});
		addChilds(3,   new int[]{19, 20, 21, 22, 23});
		addChilds(4,   new int[]{25});
		addChilds(5,   new int[]{26});
		addChilds(6,   new int[]{27});
		addChilds(7,   new int[]{28});
		addChilds(8,   new int[]{29});
		addChilds(9,   new int[]{30});
		addChilds(10,  new int[]{31});
		addChilds(11,  new int[]{32});
		addChilds(12,  new int[]{33});
		addChilds(13,  new int[]{34});
		addChilds(14,  new int[]{35});
		addChilds(15,  new int[]{36});
		addChilds(16,  new int[]{37});
		addChilds(17,  new int[]{38});
		addChilds(18,  new int[]{39, 40, 41, 42, 43});
		addChilds(19,  new int[]{44});
		addChilds(20,  new int[]{45});
		addChilds(21,  new int[]{46});
		addChilds(22,  new int[]{47});
		addChilds(23,  new int[]{48});
		addChilds(30,  new int[]{49});
		addChilds(39,  new int[]{50});
		addChilds(40,  new int[]{51});
		addChilds(41,  new int[]{52});
		addChilds(42,  new int[]{53});
		addChilds(43,  new int[]{54});
		addChilds(55,  new int[]{56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 416});
		addChilds(56,  new int[]{86});
		addChilds(57,  new int[]{87});
		addChilds(58,  new int[]{88});
		addChilds(59,  new int[]{89});
		addChilds(60,  new int[]{90});
		addChilds(61,  new int[]{91});
		addChilds(62,  new int[]{92});
		addChilds(63,  new int[]{93});
		addChilds(64,  new int[]{94});
		addChilds(65,  new int[]{95});
		addChilds(66,  new int[]{96});
		addChilds(67,  new int[]{97});
		addChilds(68,  new int[]{98});
		addChilds(69,  new int[]{99});
		addChilds(70,  new int[]{100});
		addChilds(71,  new int[]{101});
		addChilds(72,  new int[]{102});
		addChilds(73,  new int[]{103});
		addChilds(74,  new int[]{104});
		addChilds(75,  new int[]{105});
		addChilds(76,  new int[]{106});
		addChilds(77,  new int[]{107});
		addChilds(78,  new int[]{108});
		addChilds(79,  new int[]{109});
		addChilds(80,  new int[]{110});
		addChilds(81,  new int[]{111});
		addChilds(82,  new int[]{112});
		addChilds(83,  new int[]{113});
		addChilds(84,  new int[]{114});
		addChilds(85,  new int[]{115});
		addChilds(86,  new int[]{116});
		addChilds(87,  new int[]{117});
		addChilds(88,  new int[]{118});
		addChilds(89,  new int[]{119});
		addChilds(90,  new int[]{120});
		addChilds(91,  new int[]{121});
		addChilds(92,  new int[]{122});
		addChilds(93,  new int[]{123});
		addChilds(94,  new int[]{124});
		addChilds(95,  new int[]{125});
		addChilds(96,  new int[]{126});
		addChilds(97,  new int[]{127});
		addChilds(98,  new int[]{128});
		addChilds(99,  new int[]{129});
		addChilds(100, new int[]{130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 408});
		addChilds(101, new int[]{140});
		addChilds(102, new int[]{141});
		addChilds(103, new int[]{142});
		addChilds(104, new int[]{143});
		addChilds(105, new int[]{144});
		addChilds(106, new int[]{145});
		addChilds(107, new int[]{146});
		addChilds(108, new int[]{147});
		addChilds(109, new int[]{148});
		addChilds(110, new int[]{149});
		addChilds(111, new int[]{150});
		addChilds(112, new int[]{151});
		addChilds(113, new int[]{152});
		addChilds(114, new int[]{153});
		addChilds(115, new int[]{154});
		addChilds(116, new int[]{155});
		addChilds(117, new int[]{156});
		addChilds(118, new int[]{157});
		addChilds(119, new int[]{158});
		addChilds(120, new int[]{159});
		addChilds(121, new int[]{160});
		addChilds(122, new int[]{161});
		addChilds(123, new int[]{162});
		addChilds(124, new int[]{163});
		addChilds(125, new int[]{164});
		addChilds(126, new int[]{165});
		addChilds(127, new int[]{166});
		addChilds(128, new int[]{167});
		addChilds(129, new int[]{168});
		addChilds(130, new int[]{169});
		addChilds(131, new int[]{170});
		addChilds(132, new int[]{171});
		addChilds(133, new int[]{172});
		addChilds(134, new int[]{173});
		addChilds(135, new int[]{174});
		addChilds(136, new int[]{175});
		addChilds(137, new int[]{176});
		addChilds(138, new int[]{177});
		addChilds(139, new int[]{178});
		addChilds(140, new int[]{179});
		addChilds(141, new int[]{180});
		addChilds(142, new int[]{181});
		addChilds(143, new int[]{182});
		addChilds(144, new int[]{183});
		addChilds(145, new int[]{184});
		addChilds(146, new int[]{185});
		addChilds(147, new int[]{186});
		addChilds(148, new int[]{187});
		addChilds(149, new int[]{188});
		addChilds(150, new int[]{189});
		addChilds(151, new int[]{190});
		addChilds(152, new int[]{191});
		addChilds(153, new int[]{192});
		addChilds(154, new int[]{193});
		addChilds(157, new int[]{194});
		addChilds(159, new int[]{155});
		addChilds(169, new int[]{196});
		addChilds(170, new int[]{197});
		addChilds(171, new int[]{198});
		addChilds(172, new int[]{199});
		addChilds(173, new int[]{200});
		addChilds(174, new int[]{201});
		addChilds(175, new int[]{202});
		addChilds(176, new int[]{203});
		addChilds(177, new int[]{204});
		addChilds(178, new int[]{205});
		addChilds(194, new int[]{206});
		addChilds(195, new int[]{207});
		addChilds(196, new int[]{208});
		addChilds(197, new int[]{209});
		addChilds(198, new int[]{210});
		addChilds(199, new int[]{211});
		addChilds(200, new int[]{212});
		addChilds(201, new int[]{213});
		addChilds(202, new int[]{214});
		addChilds(203, new int[]{215});
		addChilds(204, new int[]{216});
		addChilds(205, new int[]{217});
		addChilds(218, new int[]{219, 220});
		addChilds(219, new int[]{221});
		addChilds(220, new int[]{222});
		addChilds(222, new int[]{223});
		addChilds(223, new int[]{224, 225, 226});
		addChilds(224, new int[]{227});
		addChilds(226, new int[]{229});
		addChilds(227, new int[]{230});
		addChilds(228, new int[]{231, 232, 233, 234, 235, 236, 237, 238});
		addChilds(230, new int[]{239});
		addChilds(231, new int[]{240});
		addChilds(232, new int[]{241});
		addChilds(233, new int[]{242});
		addChilds(234, new int[]{243});
		addChilds(235, new int[]{244});
		addChilds(236, new int[]{245});
		addChilds(237, new int[]{246});
		addChilds(238, new int[]{247});
		addChilds(239, new int[]{248});
		addChilds(248, new int[]{249});
		addChilds(249, new int[]{250});
		addChilds(250, new int[]{251});
		addChilds(252, new int[]{253});
		addChilds(253, new int[]{254});
		addChilds(254, new int[]{255, 256, 257, 258, 259, 260});
		addChilds(255, new int[]{261});
		addChilds(256, new int[]{262});
		addChilds(257, new int[]{263});
		addChilds(258, new int[]{264});
		addChilds(259, new int[]{265});
		addChilds(260, new int[]{266});
		addChilds(267, new int[]{269, 268});
		addChilds(268, new int[]{270, 271});
		addChilds(269, new int[]{272});
		addChilds(270, new int[]{273});
		addChilds(271, new int[]{274});
		addChilds(272, new int[]{275});
		addChilds(273, new int[]{276});
		addChilds(274, new int[]{277});
		addChilds(276, new int[]{278});
		addChilds(277, new int[]{279});
		addChilds(279, new int[]{280});
		addChilds(280, new int[]{281});
		addChilds(282, new int[]{283});
		addChilds(283, new int[]{284});
		addChilds(284, new int[]{285});
		addChilds(286, new int[]{287});
		addChilds(287, new int[]{288, 289});
		addChilds(290, new int[]{291});
		addChilds(292, new int[]{293});
		addChilds(294, new int[]{295});
		addChilds(295, new int[]{296});
		addChilds(296, new int[]{297});
		addChilds(298, new int[]{299});
		addChilds(299, new int[]{300});
		addChilds(300, new int[]{301});
		addChilds(302, new int[]{303});
		addChilds(303, new int[]{304});
		addChilds(305, new int[]{301});
		addChilds(306, new int[]{307});
		addChilds(307, new int[]{308});
		addChilds(309, new int[]{310});
		addChilds(310, new int[]{311});
		addChilds(311, new int[]{312});
		addChilds(313, new int[]{314});
		addChilds(314, new int[]{315});
		addChilds(315, new int[]{316});
		addChilds(317, new int[]{318, 319, 320, 321});
		addChilds(318, new int[]{322});
		addChilds(319, new int[]{325});
		addChilds(320, new int[]{323});
		addChilds(321, new int[]{324});
		addChilds(322, new int[]{326, 327, 328, 329, 330});
		addChilds(323, new int[]{331, 332});
		addChilds(324, new int[]{333});
		addChilds(325, new int[]{334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 404, 412});
		addChilds(326, new int[]{346});
		addChilds(327, new int[]{347});
		addChilds(328, new int[]{348});
		addChilds(329, new int[]{349});
		addChilds(330, new int[]{350});
		addChilds(331, new int[]{351});
		addChilds(332, new int[]{352});
		addChilds(333, new int[]{353});
		addChilds(334, new int[]{354});
		addChilds(335, new int[]{355});
		addChilds(336, new int[]{356});
		addChilds(337, new int[]{357});
		addChilds(338, new int[]{358});
		addChilds(339, new int[]{359});
		addChilds(340, new int[]{360});
		addChilds(341, new int[]{361});
		addChilds(342, new int[]{362});
		addChilds(343, new int[]{363});
		addChilds(344, new int[]{364});
		addChilds(345, new int[]{365});
		addChilds(346, new int[]{366});
		addChilds(347, new int[]{367});
		addChilds(348, new int[]{368});
		addChilds(349, new int[]{369});
		addChilds(350, new int[]{370});
		addChilds(351, new int[]{371});
		addChilds(352, new int[]{372});
		addChilds(354, new int[]{373});
		addChilds(355, new int[]{374});
		addChilds(356, new int[]{375});
		addChilds(357, new int[]{376});
		addChilds(358, new int[]{377});
		addChilds(359, new int[]{378});
		addChilds(360, new int[]{379});
		addChilds(361, new int[]{380});
		addChilds(362, new int[]{381});
		addChilds(363, new int[]{382});
		addChilds(364, new int[]{383});
		addChilds(365, new int[]{384});
		addChilds(366, new int[]{385});
		addChilds(367, new int[]{386});
		addChilds(368, new int[]{387});
		addChilds(369, new int[]{388});
		addChilds(370, new int[]{389});
		addChilds(371, new int[]{390});
		addChilds(372, new int[]{391});
		addChilds(373, new int[]{392});
		addChilds(374, new int[]{393});
		addChilds(375, new int[]{394});
		addChilds(376, new int[]{395});
		addChilds(377, new int[]{396});
		addChilds(378, new int[]{397});
		addChilds(379, new int[]{398});
		addChilds(380, new int[]{399});
		addChilds(381, new int[]{400});
		addChilds(382, new int[]{401});
		addChilds(383, new int[]{402});
		addChilds(384, new int[]{403});
		addChilds(404, new int[]{405});
		addChilds(405, new int[]{406});
		addChilds(406, new int[]{407});
		addChilds(408, new int[]{409});
		addChilds(409, new int[]{410});
		addChilds(410, new int[]{411});
		addChilds(412, new int[]{413});
		addChilds(413, new int[]{414});
		addChilds(414, new int[]{415});
		addChilds(416, new int[]{417});
		addChilds(417, new int[]{418});
		addChilds(418, new int[]{419});
                      
		armor_root.next.add(store[rec][0]);
		armor_root.next.add(store[rec][55]);
		armor_root.next.add(store[rec][218]);
		armor_root.next.add(store[rec][252]);
		armor_root.next.add(store[rec][267]);
		armor_root.next.add(store[rec][282]);
		armor_root.next.add(store[rec][286]);
		armor_root.next.add(store[rec][292]);
		armor_root.next.add(store[rec][294]);
		armor_root.next.add(store[rec][298]);
		armor_root.next.add(store[rec][302]);
		armor_root.next.add(store[rec][305]);
		armor_root.next.add(store[rec][309]);
        armor_root.next.add(store[rec][313]);
        armor_root.next.add(store[rec][317]);

	}
	
	private static void switchToArmor(){
		rec = 1;
		index = 0;
	}
	
	static void createNode(TYPE type, int value){
		store[rec][index] = new Node();
		store[rec][index].next = new ArrayList<Node>();
		store[rec][index].type = type;
		store[rec][index].value = value;
		index++;
	}
}
